module Common.Provisioning.DefaultIconSet exposing (iconSet)

import Dict exposing (Dict)


iconSet : Dict String String
iconSet =
    Dict.fromList
        [ ( "format.pdf", "file-pdf-o" )
        , ( "format.word", "file-word-o" )
        , ( "format.text", "file-text-o" )
        , ( "format.code", "file-code-o" )
        , ( "km.knowledgeModel", "database" )
        , ( "km.tag", "tag" )
        , ( "km.integration", "exchange" )
        , ( "km.itemTemplate", "file-text-o" )
        , ( "km.chapter", "book" )
        , ( "km.question", "comment-o" )
        , ( "km.answer", "check-square-o" )
        , ( "km.reference", "bookmark-o" )
        , ( "km.expert", "user-o" )
        , ( "km.fork", "code-fork" )
        , ( "kmEditor.knowledgeModel", "sitemap" )
        , ( "kmEditor.tags", "tags" )
        , ( "kmEditor.preview", "eye" )
        , ( "kmDetail.createKMEditor", "edit" )
        , ( "kmDetail.createQuestionnaire", "list-alt" )
        , ( "kmDetail.export", "download" )
        , ( "kmImport.fromFile", "upload" )
        , ( "kmImport.fromRegistry", "cloud-download" )
        , ( "menu.about", "info" )
        , ( "menu.help", "question-circle" )
        , ( "menu.kmEditor", "edit" )
        , ( "menu.knowledgeModels", "sitemap" )
        , ( "menu.logout", "sign-out" )
        , ( "menu.organization", "building" )
        , ( "menu.profile", "user" )
        , ( "menu.questionnaires", "list-alt" )
        , ( "menu.reportIssue", "exclamation-triangle" )
        , ( "menu.user", "user-circle" )
        , ( "menu.users", "users" )
        , ( "reportIssue.repository", "github" )
        ]
