module Wizard.Common.Provisioning.DefaultIconSet exposing (iconSet)

import Dict exposing (Dict)


iconSet : Dict String String
iconSet =
    Dict.fromList
        [ ( "_global.add", "fas fa-plus" )
        , ( "_global.arrowLeft", "fas fa-long-arrow-alt-left" )
        , ( "_global.arrowRight", "fas fa-long-arrow-alt-right" )
        , ( "_global.cancel", "fas fa-ban" )
        , ( "_global.delete", "fas fa-trash" )
        , ( "_global.edit", "fas fa-edit" )
        , ( "_global.error", "fas fa-exclamation-circle" )
        , ( "_global.info", "fas fa-info-circle" )
        , ( "_global.remove", "fas fa-times" )
        , ( "_global.spinner", "fas fa-spinner fa-spin" )
        , ( "_global.success", "fas fa-check" )
        , ( "_global.view", "far fa-eye" )
        , ( "_global.warning", "fas fa-exclamation-triangle" )
        , ( "colorButton.check", "fas fa-check" )
        , ( "documents.download", "fas fa-download" )
        , ( "documents.submit", "fas fa-paper-plane" )
        , ( "km.answer", "far fa-check-square" )
        , ( "km.chapter", "far fa-file" )
        , ( "km.expert", "far fa-user" )
        , ( "km.fork", "fas fa-code-branch" )
        , ( "km.integration", "fas fa-exchange-alt" )
        , ( "km.itemTemplate", "far fa-file-alt" )
        , ( "km.knowledgeModel", "fas fa-database" )
        , ( "km.question", "far fa-comment" )
        , ( "km.reference", "far fa-bookmark" )
        , ( "km.tag", "fas fa-tag" )
        , ( "kmEditor.collapseAll", "fas fa-angle-double-up" )
        , ( "kmEditor.copyUuid", "fas fa-paste" )
        , ( "kmEditor.expandAll", "fas fa-angle-double-down" )
        , ( "kmEditor.knowledgeModel", "fas fa-sitemap" )
        , ( "kmEditor.move", "fas fa-reply" )
        , ( "kmEditor.preview", "fas fa-eye" )
        , ( "kmEditor.tags", "fas fa-tags" )
        , ( "kmEditor.treeOpened", "fas fa-caret-down" )
        , ( "kmEditor.treeClosed", "fas fa-caret-right" )
        , ( "kmEditorList.continueMigration", "fas fa-long-arrow-alt-right" )
        , ( "kmEditorList.edit", "fas fa-pen" )
        , ( "kmEditorList.edited", "fas fa-pen" )
        , ( "kmEditorList.publish", "fas fa-cloud-upload-alt" )
        , ( "kmEditorList.upgrade", "fas fa-sort-amount-up" )
        , ( "kmDetail.createKMEditor", "fas fa-edit" )
        , ( "kmDetail.createQuestionnaire", "far fa-list-alt" )
        , ( "kmDetail.export", "fas fa-download" )
        , ( "kmDetail.registryLink", "fas fa-external-link-alt" )
        , ( "kmImport.file", "fas fa-file" )
        , ( "kmImport.fromFile", "fas fa-upload" )
        , ( "kmImport.fromRegistry", "fas fa-cloud-download-alt" )
        , ( "kms.upload", "fas fa-upload" )
        , ( "listing.actions", "fas fa-ellipsis-v" )
        , ( "login.externalService", "fab fa-openid" )
        , ( "menu.about", "fas fa-info" )
        , ( "menu.collapse", "fas fa-angle-double-left" )
        , ( "menu.documents", "fas fa-layer-group" )
        , ( "menu.dropdownToggle", "fas fa-angle-right" )
        , ( "menu.help", "fas fa-question-circle" )
        , ( "menu.kmEditor", "fas fa-edit" )
        , ( "menu.knowledgeModels", "fas fa-sitemap" )
        , ( "menu.logout", "fas fa-sign-out-alt" )
        , ( "menu.open", "fas fa-angle-double-right" )
        , ( "menu.profile", "fas fa-user" )
        , ( "menu.questionnaires", "fas fa-list-alt" )
        , ( "menu.reportIssue", "fas fa-exclamation-triangle" )
        , ( "menu.settings", "fas fa-cog" )
        , ( "menu.user", "fas fa-user-circle" )
        , ( "menu.users", "fas fa-users" )
        , ( "questionnaire.answeredIndication", "fas fa-check" )
        , ( "questionnaire.clearAnswer", "fas fa-undo-alt" )
        , ( "questionnaire.desirable", "far fa-check-square" )
        , ( "questionnaire.experts", "far fa-address-book" )
        , ( "questionnaire.feedback", "fas fa-exclamation" )
        , ( "questionnaire.fill", "far fa-check-square" )
        , ( "questionnaire.followUpsIndication", "fas fa-list-ul" )
        , ( "questionnaire.resourcePageReferences", "fas fa-book" )
        , ( "questionnaire.urlReferences", "fas fa-external-link-alt" )
        , ( "questionnaireList.clone", "far fa-copy" )
        , ( "questionnaireList.createDocument", "fas fa-file-import" )
        , ( "questionnaireList.createMigration", "fas fa-random" )
        , ( "questionnaireList.owner", "fas fa-user" )
        , ( "questionnaireList.viewDocuments", "fas fa-layer-group" )
        , ( "questionnaireMigration.resolve", "fas fa-check" )
        , ( "questionnaireMigration.undo", "fas fa-undo-alt" )
        , ( "report.repository", "fab fa-github" )
        , ( "userCard.icon", "far fa-user-circle" )
        ]
