version: 2
updates:
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "janslifka"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "janslifka"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/wizard-style-builder"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "janslifka"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "MarekSuchanek"
    labels:
      - "dependencies"