AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DSW Client Style Builder

Globals:
  Api:
    Cors:
      AllowMethods: "'POST, PUT, PATCH, GET, OPTIONS, DELETE, HEAD'"
      AllowHeaders: "'X-Forwarded-For,Origin,X-Requested-With,Content-Type,Accept'"
      AllowOrigin: "'*'"
      MaxAge: "'3600'"
      AllowCredentials: false
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: nodejs16.x
    Environment:
      Variables:
        AMAZON_AWS_REGION: "eu-central-1"

Resources:
  SimpleFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SimpleEvent:
          Type: Api
          Properties:
            Path: /simple
            Method: post

