name: Guide Links CI

on:
  push:
    tags:
      - v*

jobs:
  pot:
    name: Create guide links
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20 ]

    steps:
      - name: '[setup] Checkout Project'
        uses: actions/checkout@v5

      - name: '[setup] Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: '[app] Install'
        run: |
          npm ci

      - name: '[app] Create Guide Links'
        run: |
          npm run guide-links

      - name: '[release] Check Prerelease'
        id: check_prerelease
        run: |
          GITHUB_TAG=`echo $GITHUB_REF | cut -d/ -f3`
          if [[ $GITHUB_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_prerelease=false" >> "$GITHUB_OUTPUT"
          else
            echo "is_prerelease=true" >> "$GITHUB_OUTPUT"
          fi

      - name: '[release] Create & Upload Artifacts'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "guide-links.json"
          artifactContentType: application/json
          prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
          replacesArtifacts: true
